source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-sass-converter", "~> 2.0"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
end

# Windows 和 JRuby 依赖
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Windows 下用于监听文件变更
# gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# 用于 HTTP/2 和更快速的 `jekyll serve`
# gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
